<h1> Metricas de clasificación </h1>

In [2]:

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import numpy as np

<h2>Matriz de confusión </h2>

In [3]:
#Matriz de confusión para dos clases
y_prediccion =     [0, 1, 1, 1, 1, 1, 0, 0, 0, 0]
y_valores_reales = [0, 1, 1, 0, 0, 0, 1, 1, 1, 1]
print(f"Matriz de confusión:\n Esta ordenada:\n [tn fp]\n [fn tp]\n\n{confusion_matrix(y_valores_reales, y_prediccion)}")
tn, fp, fn, tp = confusion_matrix(y_valores_reales, y_prediccion).ravel()
print(f"\nVerdadero Positivo: {tp}\nFalso positivo: {fp} \nFalso negatico: {fn}\nVerdadero negativo: {tn}")

Matriz de confusión:
 Esta ordenada:
 [tn fp]
 [fn tp]

[[1 3]
 [4 2]]

Verdadero Positivo: 2
Falso positivo: 3 
Falso negatico: 4
Verdadero negativo: 1


In [4]:
#Tambien se puede hacer la matriz de confusión clases mayor a 2
y_prediccion = [0, 1, 1, 3, 2, 3, 1, 2, 3, 0]
y_valores_reales = [0, 1, 2, 3, 1, 2, 3, 2, 3, 0]
print(f"Matriz de confusión:\n {confusion_matrix(y_valores_reales, y_prediccion)}")

Matriz de confusión:
 [[2 0 0 0]
 [0 1 1 0]
 [0 1 1 1]
 [0 1 0 2]]


<h2> Metrica de precisión</h2>

In [5]:
#Usando la metrica de clasificación acurracy score
y_prediccion = [0, 1, 1, 3, 2, 3, 1, 2, 3, 0]
y_valores_reales = [0, 1, 2, 3, 1, 2, 3, 2, 3, 0]
print(f"Puntaje de Precisión: {accuracy_score(y_valores_reales, y_prediccion)}")

Puntaje de Precisión: 0.6


<h2>Función que devuelve varias metricas juntas "classification_report"</h2>

In [6]:
y_prediccion =     [0, 1, 1, 3, 2, 3, 1, 2, 3, 0, 4, 2, 1, 4, 2]
y_valores_reales = [0, 1, 4, 2, 3, 1, 2, 3, 2, 3, 0, 1, 4, 4, 2]
nombre_clases = ['Clase 0','Clase 1', 'Clase 2', 'Clase 3', 'Clase 4']
print(f"Classification Report:\n{classification_report(y_valores_reales, y_prediccion,target_names=nombre_clases)}")

Classification Report:
              precision    recall  f1-score   support

     Clase 0       0.50      0.50      0.50         2
     Clase 1       0.25      0.33      0.29         3
     Clase 2       0.25      0.25      0.25         4
     Clase 3       0.00      0.00      0.00         3
     Clase 4       0.50      0.33      0.40         3

    accuracy                           0.27        15
   macro avg       0.30      0.28      0.29        15
weighted avg       0.28      0.27      0.27        15

